#!/usr/bin/env python
# -*- coding: utf-8 -*-"
# vim: set expandtab tabstop=2 shiftwidth=2:

from core.main import captchonka

if __name__ == "__main__":
  app = captchonka()
  app.create_options()
  app.run()
